# Generated by Django 5.2.10 on 2026-02-03 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon_content', models.TextField(help_text='Raw SVG XML', verbose_name='Icon Content')),
                ('category', models.CharField(choices=[('LIFETIME', 'Lifetime'), ('PERIODIC', 'Periodic'), ('STREAK', 'Streak')], default='LIFETIME', max_length=20, verbose_name='Category')),
                ('event_type', models.CharField(choices=[('SUCHAR_POSTED', 'Suchar Posted'), ('VOTE_RECEIVED', 'Vote Received'), ('VOTE_CAST', 'Vote Cast')], default='SUCHAR_POSTED', max_length=20, verbose_name='Event Type')),
                ('metric', models.CharField(choices=[('COUNT_SUCHAR', 'Suchar Count'), ('COUNT_VOTE_FUNNY', 'Funny Vote Count'), ('COUNT_VOTE_DRY', 'Dry Vote Count'), ('COUNT_VOTE_CAST', 'Vote Cast Count'), ('SUM_SCORE', 'Total Score')], default='COUNT_SUCHAR', max_length=20, verbose_name='Metric')),
                ('threshold', models.PositiveIntegerField(default=1, verbose_name='Threshold')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False, verbose_name='Seen by user')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
