# Generated by Django 5.2.10 on 2026-02-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_initial_achievements_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='theme',
            field=models.CharField(blank=True, help_text="E.g. 'Christmas', 'Programming'. Leave blank for general.", max_length=100, verbose_name='Theme'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='tier',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum'), (5, 'Diamond')], default=0, help_text='Difficulty/Rarity tier of the achievement', verbose_name='Tier'),
        ),
    ]
