# Generated by Django 5.2.10 on 2026-02-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_achievement_theme_achievement_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='metric',
            field=models.CharField(choices=[('COUNT_SUCHAR', 'Suchar Count'), ('COUNT_VOTE_FUNNY', 'Funny Vote Count'), ('COUNT_VOTE_DRY', 'Dry Vote Count'), ('COUNT_VOTE_CAST', 'Vote Cast Count'), ('SUM_SCORE', 'Total Score'), ('NIGHT_OWL', 'Night Owl'), ('STREAK_LOGIN', 'Login Streak'), ('POLARIZER', 'Polarizer')], default='COUNT_SUCHAR', max_length=20, verbose_name='Metric'),
        ),
    ]
