# Generated by Django 5.2.10 on 2026-02-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_achievement_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_secret',
            field=models.BooleanField(default=False, help_text='If checked, name and description are hidden until unlocked.', verbose_name='Secret Achievement'),
        ),
    ]
