# Generated by Django 5.2.10 on 2026-05-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_achievement_frontend_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='description_pl',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='theme_en',
            field=models.CharField(blank=True, help_text="E.g. 'Christmas', 'Programming'. Leave blank for general.", max_length=100, null=True, verbose_name='Theme'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='theme_pl',
            field=models.CharField(blank=True, help_text="E.g. 'Christmas', 'Programming'. Leave blank for general.", max_length=100, null=True, verbose_name='Theme'),
        ),
    ]
