# Generated by Django 6.0.6 on 2026-08-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0010_achievement_translation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='tier',
            field=models.IntegerField(choices=[(0, 'Common'), (1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum'), (5, 'Diamond')], default=0, help_text='Difficulty/Rarity tier of the achievement', verbose_name='Tier'),
        ),
    ]
