# Generated by Django 6.0.6 on 2026-08-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0011_alter_achievement_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True, verbose_name='Job ID')),
                ('ran_at', models.DateTimeField(verbose_name='Ran At')),
            ],
            options={
                'verbose_name': 'Scheduler Run',
                'verbose_name_plural': 'Scheduler Runs',
            },
        ),
    ]
