# Generated by Django 6.0.6 on 2026-08-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0012_schedulerrun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulerrun',
            options={'ordering': ('job_id',), 'verbose_name': 'Scheduler Run', 'verbose_name_plural': 'Scheduler Runs'},
        ),
    ]
