# Generated by Django 6.1 on 2026-09-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0015_seed_yearly_scheduler_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='metric',
            field=models.CharField(choices=[('COUNT_SUCHAR', 'Suchar Count'), ('COUNT_VOTE_FUNNY', 'Funny Vote Count'), ('COUNT_VOTE_DRY', 'Dry Vote Count'), ('COUNT_VOTE_CAST', 'Vote Cast Count'), ('SUM_SCORE', 'Total Score'), ('NIGHT_OWL', 'Night Owl'), ('STREAK_LOGIN', 'Login Streak'), ('POLARIZER', 'Polarizer'), ('DRY_MASTER', 'Dry Master'), ('FRONTEND_EVENT', 'Frontend Event')], default='COUNT_SUCHAR', max_length=20, verbose_name='Metric'),
        ),
    ]
