# Generated by Django 6.1.1 on 2026-09-09 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0023_publika_rozgrzana_achievement_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'is_seen'], name='achievement_user_id_1f5e29_idx'),
        ),
    ]
