"""Every class the SCSS defines is used somewhere (#503, epic #502).

Dead rules ship to every visitor and hide which classes the pages really depend on. The check reads
the sources only (no build, no Node): classes come from the selectors in ``webpack/src/scss/``, and a
class counts as used when its name appears as a whole token in a template, in ``webpack/src/js/`` or
in Python outside tests and migrations. Names built at runtime are covered by ``DYNAMIC_PREFIXES``,
and classes only a third-party library puts on the DOM by ``EXTERNAL_CLASSES``/``EXTERNAL_PREFIXES``.
"""

import re
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_SCSS = _ROOT / "webpack/src/scss"

# A class built at runtime (`tier-{{ n }}`, `'rank-' + name`) never appears whole in the sources.
DYNAMIC_PREFIXES = ("tier-", "rank-", "toast-")

# Generated by flatpickr in JS (the block in pages/suchar_form.scss), so no template or script of ours
# names them. They are not dead.
EXTERNAL_PREFIXES = ("flatpickr-",)
EXTERNAL_CLASSES = frozenset(
    {
        "cur-year",
        "inRange",
        "startRange",
        "endRange",
        "prevMonthDay",
        "nextMonthDay",
    },
)

_COMMENT_RE = re.compile(r"/\*.*?\*/|(?<![:'\"(])//[^\n]*", re.DOTALL)
_PRELUDE_RE = re.compile(r"([^{};]+)\{")
_CLASS_RE = re.compile(r"(?<![\w.])\.(-?[A-Za-z_][\w-]*)")
_SOURCE_SUFFIXES = {".html", ".svg", ".txt", ".js", ".py"}


def selector_classes(scss: str) -> set[str]:
    """The class names in the selectors of one stylesheet (comments and at-rule preludes skipped)."""
    names: set[str] = set()
    for prelude in _PRELUDE_RE.findall(_COMMENT_RE.sub("", scss)):
        if not prelude.lstrip().startswith("@"):
            names.update(_CLASS_RE.findall(prelude))
    return names


def _usage_files() -> list[Path]:
    files = [p for p in (_ROOT / "suchar_overflow").rglob("*") if "templates" in p.parts and p.is_file()]
    files += (_ROOT / "webpack/src/js").rglob("*.js")
    for path in (_ROOT / "suchar_overflow").rglob("*.py"):
        parts = set(path.relative_to(_ROOT).parts)
        if parts & {"tests", "migrations"} or path.name in {"conftest.py"} or path.name.startswith("test_"):
            continue
        files.append(path)
    for path in (_ROOT / "config").rglob("*.py"):
        files.append(path)
    return [p for p in files if p.suffix in _SOURCE_SUFFIXES]


def unused_classes(defined: set[str], corpus: str) -> list[str]:
    unused = []
    for name in sorted(defined):
        if name.startswith(DYNAMIC_PREFIXES + EXTERNAL_PREFIXES) or name in EXTERNAL_CLASSES:
            continue
        if not re.search(rf"(?<![\w-]){re.escape(name)}(?![\w-])", corpus):
            unused.append(name)
    return unused


def _corpus() -> str:
    return "\n".join(p.read_text(encoding="utf-8", errors="ignore") for p in _usage_files())


def test_every_scss_class_is_used() -> None:
    defined: set[str] = set()
    for path in _SCSS.rglob("*.scss"):
        defined |= selector_classes(path.read_text(encoding="utf-8"))
    assert len(defined) > 300  # the extraction found the stylesheets, not an empty set
    assert unused_classes(defined, _corpus()) == [], (
        "SCSS defines classes no template, script or Python module uses: delete the rule, or if a "
        "library generates the class, add it to EXTERNAL_CLASSES with the reason (#503)"
    )


def test_unused_class_is_reported() -> None:
    # Negative control: the check must go red for a class defined but never used, also inside @media.
    scss = ".used-one { color: red; }\n@media (min-width: 1px) { .never-used-xyz:hover { color: blue; } }\n"
    names = selector_classes(scss)
    assert names == {"used-one", "never-used-xyz"}
    assert unused_classes(names, '<div class="used-one">') == ["never-used-xyz"]


def test_dynamic_and_external_classes_are_exempt() -> None:
    names = {"tier-gold", "rank-3", "toast-info", "flatpickr-day", "inRange", "plain-dead"}
    assert unused_classes(names, "") == ["plain-dead"]
