# Generated by Django 5.2.10 on 2026-01-25 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_change_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
