# Generated by Django 5.2.10 on 2026-01-25 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_change_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_change_secret',
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('revocation_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Change Request',
                'verbose_name_plural': 'Email Change Requests',
            },
        ),
    ]
