# Generated by Django 5.2.10 on 2026-01-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_email_change_secret_emailchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchangerequest',
            name='old_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('revoked', 'Revoked')], default='pending', max_length=10),
        ),
    ]
