# Generated by Django 5.2.10 on 2026-01-23 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suchar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Suchar text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suchary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('suchar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='suchary.suchar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suchar_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('suchar', 'user')},
            },
        ),
    ]
