# Generated by Django 5.2.10 on 2026-02-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suchary', '0002_tag_suchar_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_dry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_funny',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(blank=True, choices=[(1, 'Up'), (-1, 'Down')], null=True),
        ),
    ]
