# Generated by Django 5.2.10 on 2026-02-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suchary', '0004_migrate_old_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='value',
        ),
    ]
