# Generated by Django 5.2.10 on 2026-02-01 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suchary', '0005_remove_vote_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='suchar',
            name='published_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Publication Date'),
        ),
    ]
