# Generated by Django 6.1 on 2026-08-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suchary', '0007_suchar_text_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suchar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
