# Generated by Django 6.1 on 2026-09-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suchary', '0008_alter_suchar_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='suchar',
            name='is_overdried',
            field=models.BooleanField(default=False, help_text='Latched by the achievement engine when the suchar drew >=10 dry votes and no funny votes within an hour of publication. Never cleared — the frontend uses it for the craquelure overlay.', verbose_name='Overdried'),
        ),
    ]
