# Generated by Django 6.1 on 2026-09-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suchary', '0009_suchar_is_overdried'),
    ]

    operations = [
        migrations.AddField(
            model_name='suchar',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, help_text="Incremented on every successful save from the edit view. Drives the 'Recydywa' achievement (5 edits of one suchar). Never decremented — the engine only awards.", verbose_name='Edit count'),
        ),
    ]
